# Generated by Django 4.1.3 on 2022-12-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='personal.png', null=True, upload_to=''),
        ),
    ]
